2020-11-30 12:39:22,975--test_login.py--48--ERROR--hanjiping_log--用例登录成功出现错误，错误信息为：0 != 2 within 7 places (2 difference)
2020-11-30 12:39:22,976--test_login.py--49--ERROR--hanjiping_log--0 != 2 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_login.py", line 44, in test_login
    self.assertAlmostEqual(expected['code'],res["code"])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 0 != 2 within 7 places (2 difference)
2020-11-30 12:39:23,300--test_login.py--52--INFO--hanjiping_log--用例运行正常密码错误
2020-11-30 12:39:23,401--test_login.py--52--INFO--hanjiping_log--用例运行正常账号不是标准的手机号
2020-11-30 12:39:24,565--test_register.py--70--INFO--hanjiping_log--注册成功-带注册名该条用例通过
2020-11-30 12:39:25,591--test_register.py--70--INFO--hanjiping_log--成功-不带用户名该条用例通过
2020-11-30 12:39:25,688--test_register.py--70--INFO--hanjiping_log--不输入手机号该条用例通过
2020-11-30 12:39:25,787--test_register.py--70--INFO--hanjiping_log--手机号长度10位该条用例通过
2020-11-30 12:39:25,886--test_register.py--70--INFO--hanjiping_log--手机号长度12位该条用例通过
2020-11-30 12:39:25,980--test_register.py--70--INFO--hanjiping_log--手机号含有非法字符该条用例通过
2020-11-30 12:39:26,308--test_register.py--70--INFO--hanjiping_log--已注册过的手机号该条用例通过
2020-11-30 12:39:26,704--test_register.py--70--INFO--hanjiping_log--密码7位该条用例通过
