2020-11-28 23:17:54,985--test_login.py--48--ERROR--hanjiping_log--用例登录成功出现错误，错误信息为：0 != 2 within 7 places (2 difference)
2020-11-28 23:17:54,986--test_login.py--49--ERROR--hanjiping_log--0 != 2 within 7 places (2 difference)
Traceback (most recent call last):
  File "/Users/hanjiping/PycharmProjects/Port_test01/TestCase/test_login.py", line 44, in test_login
    self.assertAlmostEqual(expected['code'],res["code"])
  File "/opt/anaconda3/lib/python3.7/unittest/case.py", line 906, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 0 != 2 within 7 places (2 difference)
2020-11-28 23:17:55,277--test_login.py--52--INFO--hanjiping_log--用例运行正常密码错误
2020-11-28 23:17:55,369--test_login.py--52--INFO--hanjiping_log--用例运行正常账号不是标准的手机号
2020-11-28 23:17:56,192--test_register.py--70--INFO--hanjiping_log--注册成功-带注册名该条用例通过
2020-11-28 23:17:57,120--test_register.py--70--INFO--hanjiping_log--成功-不带用户名该条用例通过
2020-11-28 23:17:57,218--test_register.py--70--INFO--hanjiping_log--不输入手机号该条用例通过
2020-11-28 23:17:57,316--test_register.py--70--INFO--hanjiping_log--手机号长度10位该条用例通过
2020-11-28 23:17:57,418--test_register.py--70--INFO--hanjiping_log--手机号长度12位该条用例通过
2020-11-28 23:17:57,509--test_register.py--70--INFO--hanjiping_log--手机号含有非法字符该条用例通过
2020-11-28 23:17:57,839--test_register.py--70--INFO--hanjiping_log--已注册过的手机号该条用例通过
2020-11-28 23:17:58,236--test_register.py--70--INFO--hanjiping_log--密码7位该条用例通过
2020-11-28 23:17:58,551--test_register.py--70--INFO--hanjiping_log--密码17位该条用例通过
2020-11-28 23:17:58,954--test_register.py--70--INFO--hanjiping_log--不输入密码该条用例通过
